steps:
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - clone
#   - --recurse-submodules
#   - git@github.com:kaizu/uplift
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-test:0.1', '.']

images: ['gcr.io/$PROJECT_ID/gcp-test:0.1']
